typography_spectrum: 0.7753507487941533
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15349344932474196
  lightness: 0.9053220152854919
  saturation: 0.9407878557685763
  rhythmicContrast: 0.1370441010221839
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9937556234654039
analytics:
  google: null
  facebook: null
  twitter: null
name: airpay
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: apFX
purpose: []
